name: SkywarsLobby
main: net.omniblock.lobbies.skywars.SkywarsLobbyPlugin
softdepend: [OmniNetwork, OmniLobbies, HolographicDisplays, Citizens, NoteBlockAPI, ShopHandler]
version: 4.6.2
commands:
   lobby:
      description: Comando para volver al lobby principal.
   hub:
      description: Comando para volver al lobby principal.
   abandonar:
      description: Comando para volver al lobby principal.
   salir:
      description: Comando para volver al lobby principal.
